// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwsodkowmaidwoihxxyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3c29ka293bWFpZHdvaWh4eHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjQ1OTYsImV4cCI6MjA2NzA0MDU5Nn0.yyxHDuP2ddMwgNys4UDp6hOxZIlFMrWyzkb-RujJdhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});